name: E2E (Playwright)

on:
  workflow_dispatch:
  push:
    branches: [ workshop/solution ]
    paths-ignore:
      - '**/README.md'
      - README.md
      - .gitignore
      - LICENSE
  pull_request:
    branches: [ workshop/solution ]
    paths-ignore:
      - '**/README.md'
      - README.md
      - .gitignore
      - LICENSE

jobs:
  adyen-step-by-step-integration-workshop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project with Gradle
        run: ./gradlew build
      - name: Build project image
        run: docker build -t adyen-step-by-step-integration-workshop:latest .
      - name: Start adyen-step-by-step-integration-workshop container
        run: docker run --rm -d --name adyen-step-by-step-integration-workshop -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} adyen-step-by-step-integration-workshop:latest
      - name: Run testing suite
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=workshop -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main
